# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Generate release

on:
  push:
    tags:
      - 'v*'

jobs:

  build:
    runs-on: ubuntu-latest    
    steps:

    - name: Get tag version
      id: get_version
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        cache: 'npm'

    - name: Install npm
      run: npm ci

    - name: Rollup
      run: npm run rollup

    - name: ZIP build 
      uses: montudor/action-zip@v1
      with:
        args: zip -qq -r openlime-${{ env.RELEASE_VERSION }}.zip build

    - name: Create commits list
      run: jsdoc/releases/gen_changelog.sh >> jsdoc/releases/rel-${{ env.RELEASE_VERSION }}.md

    - name: Create automatic release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "openlime-${{ env.RELEASE_VERSION }}.zip"
        bodyFile: "jsdoc/releases/rel-${{ env.RELEASE_VERSION }}.md"
        token: ${{ secrets.GITHUB_TOKEN }}
