name: GitHub pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
      - run: npm install ink-docstrap

      - name: JSDoc Action
        uses: andstor/jsdoc-action@v1.2.1
        with:
          source_dir: ./
          output_dir: ./docs
          template: ink-docstrap
          front_page: README.md

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
