name: GitHub pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: JSDoc Action
        uses: andstor/jsdoc-action@v1.2.1
        with:
          output_dir: ./docs
          template: ink-docstrap
          front_page: README.md
          recurse: false

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./docs
