# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Generate release

on:
  push:
    tags:
      - 'v*'

jobs:

  build:
    runs-on: ubuntu-latest    
    steps:

    - name: Get tag version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        cache: 'npm'

    - name: Install npm
      run: npm ci

    - name: Rollup
      run: npm run rollup

    - name: ZIP build 
      uses: montudor/action-zip@v1
      with:
        args: zip -qq -r openlime-${{ steps.get_version.outputs.VERSION }}.zip build

    - name: Create automatic release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: openlime-${{ steps.get_version.outputs.VERSION }}.zip

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: openlime-${{ steps.get_version.outputs.VERSION }}.zip
        tag: ${{ github.ref }}
        overwrite: true
